[profile.default]
src = "src"
out = "out"
libs = ["lib"]
verbosity=5
ffi=true
[rpc_endpoints]
mumbai = "${MUMBAI_RPC}"

[etherscan]
mumbai = { key = "${POLYGONSCAN_API}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config